### PR TITLE
feat: Rewritten both opened pull requests

### PR DESCRIPTION
**Pull request by imranbarbhuiya**
I've rewritten both the opened pull requests

- [x]  #50 
- [x]  #45 
- [x] updated types and readme
- [ ] didn't update change log and version

**But I'm not getting a way to test them out. Can you make a beta release of this pr, so that I can test it.**

### CODE REVIEW

**Comment by imranbarbhuiya** [comment]
I didn't tested the changes. Make a beta release so that I can test this out.
I didn't change version or change log.

This release adds two new features

- auto complete for advanced options 
- nonce support 

So we can make a minor release as advised in  [semver](https://semver.org/).

**Comment by apal21** [comment]
Did you try with `npm link` locally?

**Comment by imranbarbhuiya** [comment]
Functional component is showing some error related to hook. I'm not able to fix it. Problem is babel is adding useEffect inside of render, which isn't valid, so I'm going to add nonce only for now.

**Comment by apal21** [comment]
Okay cool

**Comment by imranbarbhuiya** [comment]
I'm using `npm link` for the first time, and It seems like it's showing errors in the stable release also. I tried with the previous version which is working fine when installing with `npm install` but trowing errors when using link. 
image

**Pull request closed without merging**
