### PR TITLE
Add start delay.

### PR DESCRIPTION
**Pull request by jacknight**
This feature was previously implemented incorrectly where it left the code open to race conditions where `NProgress.done()` might not be called even though `NProgress.start()` had been, because _multiple_ start timers could be queued up. It was also possible for a stop timer to be set, and then a start timer to also be set before the stop timer fired.

The solution is to kill both the start and stop timers whenever a router event fires, and only call `NProgress.done()` when `NProgress.isStarted()` returns true _within_ the stopTimer. That way you can be sure `NProgress.done()` is called always and only when `NProgress.start()` has been called first.

### CODE REVIEW

**Comment by PabloSzx** [comment]
@apal21 any news on accepting this PR?

**Comment by apal21** [comment]
@PabloSzx I can see why we need stopDelay. But why do we need a start delay?

**Comment by jacknight** [comment]
If you don’t want the progress bar to appear for pages which load quickly.

**Comment by apal21** [comment]
If we want our progress bar to appear for a little longer, we can always add stopDelay. I don't see why we need to see the progress bar after some time. What are we trying to achieve here? What am I missing?

**Comment by jacknight** [comment]
The progress bar appears no matter how fast the page loads. If you add a
start delay, it won’t appear at all of the page loads more quickly than the
start delay. The goal is to not have the progress bar appear at all for
quick loading pages.

**Comment by apal21** [comment]
Got it! But adding the start delay is not an elegant solution.
Let's say if you add a delay of 1 second and your page takes 2 seconds to load completely. In such cases, it'd feel like the link/button click is propagating slowly or in other words, the page is laggy. Which is not a good user experience.

**Comment by jacknight** [comment]
I don’t agree, but that’s your call.

**Comment by freddieerg** [comment]
I agree with @jacknight here. I think this is an absolutely essential feature. To me, especially with the project I am working on right now, it makes absolutely no sense for 90% of my pages to show a loading indicator as all the content on those pages is already client side and will be loading in less than 300ms. 

With all due respect @apal21 surely this is just a matter of opinion and should be a feature that the developer is able to decide for themselves whether or not they want to use?

**Comment by apal21** [comment]
@freddieerg I'm not against having this feature but the way we're trying to implement is not elegant as I mentioned in the comment above. If you have any better ideas we can implement them.

**Comment by freddieerg** [comment]
What is it exactly you don't thing is elegant sorry? I've reviewed the PR and it seems to be a working solution?

**Comment by freddieerg** [comment]
Actually don't worry if you don't want to implement it. @jacknight has [published his fork to NPM](https://www.npmjs.com/package/nextjs-progressbar-withdelay) with the delayMs option.

**Comment by apal21** [comment]
Awesome!

**Pull request closed without merging**
