### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shmidtelson**
fix: Syntax error has been fixed in an example

### CODE REVIEW

**Review by imranbarbhuiya — COMMENTED** [review]
It was imported as `NextNProgress` so it should be used as `NextNProgress`

```jsx
import NextNProgress from 'nextjs-progressbar';

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <NextNProgress />
      <Component {...pageProps} />;
    </>
  );
}
```

[How to use](https://github.com/apal21/nextjs-progressbar#how-to-use)

**Comment by shmidtelson** [comment]
Why is it different? 
I got error, because i copied from one place `import` and from other place `<NextNProgress/>`

**Comment by imranbarbhuiya** [comment]
> Why is it different? I got error, because i copied from one place `import` and from other place `<NextNProgress/>`

It's upto you what you wanna name it. You can give anything in import and later on you need to use the same name what you've used in import.

**Comment by imranbarbhuiya** [comment]
Now I understood what you were saying. In Readme.md, both `NextNprogress` and `NextNProgress` were present. Thank you for the PR, but this PR needs some more changes, so I've included these changes in my PR. Will be fixed in next patch update.

**Comment by shmidtelson** [comment]
@imranbarbhuiya 
Ok! Thank you for detailed answer. I`ve just wanted to make a bit better your project

**Comment by imranbarbhuiya** [comment]
Fixed in #59

**Pull request closed without merging**
