### PR TITLE
feat: minor changes

### PR DESCRIPTION
**Pull request by imranbarbhuiya**
All the changes
- Added nprogress types
- code refactored
- updated babel
- added lint-staged with eslint and prettier

### CODE REVIEW

**Comment by imranbarbhuiya** [comment]
All the changes
- Added nprogress types
- code refactored
- updated babel
- added lint-staged with eslint and prettier


@apal21 here's complete change log, please review 

One thing left is updating to next v12.0.2 to remove all the warnings in `npm install` which isn't released yet.

**Comment by imranbarbhuiya** [comment]
I've a question also why the version name is like this and not 1.0.0?
Just asking 😃 .

**Comment by apal21** [comment]
Thanks a lot for putting in so much effort. Really appreciate that.

> why the version name is like this and not 1.0.0?

When I published this package, I didn't know that people are actually going to use it. So just for testing, I started releasing from v0.0.1 to learn how to publish a package and what to do next.

After 3-4 months, I realized that a lot of people are using this package. Since all the changes are backward compatible and if someone has already installed these versions, they won't get the new update even if it is not causing any issues. Hence, I continued with v0.0.x

**Comment by imranbarbhuiya** [comment]
> I continued with v0.0.x
Got you. 

And thank you for this awesome package ❤️.

**Comment by imranbarbhuiya** [comment]
Why your readme isn't showing in npm?

**Comment by imranbarbhuiya** [comment]
Here we go. I've updated to next v12.0.0 which have removed all the warning showing during `npm intall`.

@apal21 Review my changes. I hope everything is perfect and there is no breaking changes.

For this pr, this is the last commit. I'll definitely open more PRs if I find anything which can be improved or changed.
Let me know if you want me to remove anything which I've added.

**This PR doesn't change any code codes. It's more focused on DX.**

I'm resending a complete change log of this PR.

**Comment by imranbarbhuiya** [comment]
# Changelog

- Added nprogress option types.
- code refactored
- updated babel
- added lint-staged with eslint and prettier
- updated node js
- npmignore updated

**Comment by imranbarbhuiya** [comment]
# Changelog

- Added nprogress option types.
- code refactored
- updated babel
- added lint-staged with eslint and prettier
- updated next js
- npmignore updated

**Comment by apal21** [comment]
Hey, since you are putting a lot of effort here and I am not getting enough time to work on this, would you like to be a collaborator for this repo?

**Comment by imranbarbhuiya** [comment]
Yeah, sure. Thank you for the opportunity.

**Comment by apal21** [comment]
Done. Check your email.

**Review by apal21 — APPROVED** [review]

**Pull request merged**
