### PR TITLE
feat: use react.memo and allow custom css tag

### LINKED ISSUE #74: export css file rather than injecting style tag
Would it be possible to do what some other libraries do (namely, react-tippy) and export a css file rather than injecting a script tag? This way next can handle the styles, minify and bundle them with the other styles.

For backwards compatibility, you could have a prop called `injectStyles` and have it default to true. If you'd like

Lmk what you think :)

[Reference (react-tippy)](https://github.com/tvkhoa/react-tippy#how-to-use):
First, you need import css
```ts
import 'react-tippy/dist/tippy.css'
```

**Edit:** After revisiting, I see that the reason this is probably done is because color and height are injected into the css from the params passed by the user. I'm not against this, but I think that the style tag should atleast be minified.

 https://github.com/apal21/nextjs-progressbar/blob/a122fd2303b26121f6c6a54fd1e45ad7f473ad1b/src/index.tsx#L109

### PR DESCRIPTION
**Pull request by imranbarbhuiya**
This pr

- migrates to yarn v3
- uses `React.memo` for better perf
- allows passing custom jsx element for styling. This can also be used to pass a minified css.

partially fixes #74, #79 

### Using `@emotion/react`
```tsx
import NextNProgress from "nextjs-progressbar";
import { css, Global } from '@emotion/react';

const transformCSS = (cssString: string) => {
       const style = css`${cssString}`;
       return <Global styles={style} />
}

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <NextNProgress transformCSS={transformCSS}  />
      <Component {...pageProps} />;
    </>
  );
}
```

### Without using any package
Create a css file with the following content.

<details>
  <summary>nprogress.css</summary>

```css
#nprogress {
        pointer-events: none;
      }
      #nprogress .bar {
        background: #29D;
        position: fixed;
        z-index: 9999;
        top: 0;
        left: 0;
        width: 100%;
        height: 3px;
      }
      #nprogress .peg {
        display: block;
        position: absolute;
        right: 0px;
        width: 100px;
        height: 100%;
        box-shadow: 0 0 10px #29D, 0 0 5px #29D;
        opacity: 1;
        -webkit-transform: rotate(3deg) translate(0px, -4px);
        -ms-transform: rotate(3deg) translate(0px, -4px);
        transform: rotate(3deg) translate(0px, -4px);
      }
      #nprogress .spinner {
        display: block;
        position: fixed;
        z-index: 1031;
        top: 15px;
        right: 15px;
      }
      #nprogress .spinner-icon {
        width: 18px;
        height: 18px;
        box-sizing: border-box;
        border: solid 2px transparent;
        border-top-color: #29D;
        border-left-color: #29D;
        border-radius: 50%;
        -webkit-animation: nprogresss-spinner 400ms linear infinite;
        animation: nprogress-spinner 400ms linear infinite;
      }
      .nprogress-custom-parent {
        overflow: hidden;
        position: relative;
      }
      .nprogress-custom-parent #nprogress .spinner,
      .nprogress-custom-parent #nprogress .bar {
        position: absolute;
      }
      @-webkit-keyframes nprogress-spinner {
        0% {
          -webkit-transform: rotate(0deg);
        }
        100% {
          -webkit-transform: rotate(360deg);
        }
      }
      @keyframes nprogress-spinner {
        0% {
          transform: rotate(0deg);
        }
        100% {
          transform: rotate(360deg);
        }
      }
```
</details>

And in `_app.tsx`

```tsx
import NextNProgress from "nextjs-progressbar";
import 'path/to/nprogress.css';

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <NextNProgress  transformCSS={() => <></>} />
      <Component {...pageProps} />;
    </>
  );
}
```

### CODE REVIEW

**Comment by apal21** [comment]
Need to update `versioin` in package.json

**Comment by imranbarbhuiya** [comment]
done

**Review by apal21 — APPROVED** [review]

**Comment by DragoshDX** [comment]
it looks like that transformCSS prop is not available in the 0.0.15 release 
I see now that currently on the repo the version is 0.0.16, however uninstalling and re-installing@latest still downloads 0.0.15 
while trying to force it on .16: 

$ npm i nextjs-progressbar@0.0.16
npm ERR! code ETARGET
npm ERR! notarget No matching version found for nextjs-progressbar@0.0.16.

**Comment by imranbarbhuiya** [comment]
`0.0.16` isn't released yet.

**Comment by apal21** [comment]
@DragoshDX it is released now to npm.

**Comment by DragoshDX** [comment]
thank you for your work

**Pull request merged**
